global:
  scrape_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['docker.for.mac.localhost:8080']
    metrics_path: '/actuator/prometheus'
